using System.Collections.Generic;
using System.Threading.Tasks;
using DIHL.DTOs;
using Refit;

namespace DIHL.Client.WebApiRepository.Clients
{
    public interface ILeagueApi
    {
        /// <summary>
        /// Lists all the league records.
        /// </summary>
        /// <returns></returns>
        [Get("/league")]
        Task<IList<LeagueDTO>> List();

        /// <summary>
        /// Gets the specified league.
        /// </summary>
        /// <param name="id">The league identifier.</param>
        /// <returns></returns>
        [Get("/league/{id}")]
        Task<LeagueDTO> Get(int id);


        /// <summary>
        /// Upserts an league record.
        /// The league id is generated by the server.
        /// </summary>
        /// <param name="value">The entity data.</param>
        /// <returns></returns>
        [Post("/league")]
        Task<LeagueDTO> Post([Body]LeagueDTO value);

        /// <summary>
        /// Puts the posted league data at the specific location.
        /// </summary>
        /// <param name="id">The Id to assign to the league.</param>
        /// <param name="value">The league data.</param>
        /// <returns></returns>
        [Put("/league/{id}")]
        Task<LeagueDTO> Put(int id, [Body]LeagueDTO value);

        /// <summary>
        /// Deletes the specified league.
        /// </summary>
        /// <param name="id">The league identifier.</param>
        /// <returns></returns>
        [Delete("/league/{id}")]
        Task<bool> Delete(int id);
    }
}
