using DIHL.Application.Core.Interfaces;
using DIHL.DTOs;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace DIHL.Application.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/League")]
    [Authorize]
    public class LeagueController : BaseApiController
    {
        private readonly ILeagueService _leagueService;
        private readonly ILogger _log = Log.ForContext<LeagueController>();

        public LeagueController(ILeagueService leagueService)
        {
            _leagueService = leagueService;
        }

        /// <summary>
        /// Lists all the league records.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ProducesResponseType(typeof(List<LeagueDTO>), 200)]
        public async Task<IActionResult> List()
        {
            IActionResult result = await Execute(_log, async () => await _leagueService.List());
            return result;
        }

        /// <summary>
        /// Gets the specified league.
        /// </summary>
        /// <param name="id">The league identifier.</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(LeagueDTO), 200)]
        public async Task<IActionResult> Get(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _leagueService.Get(id));
            return result;
        }

        /// <summary>
        /// Upserts an league record.
        /// The league id is generated by the server.
        /// </summary>
        /// <param name="value">The entity data.</param>
        /// <returns></returns>
        [HttpPost]
        [ProducesResponseType(typeof(LeagueDTO), 200)]
        public async Task<IActionResult> Post([FromBody]LeagueDTO value)
        {
            IActionResult result = await Execute(_log, async () => await _leagueService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Puts the posted league data at the specific location.
        /// </summary>
        /// <param name="id">The Id to assign to the league.</param>
        /// <param name="value">The league data.</param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(LeagueDTO), 200)]
        public async Task<IActionResult> Put(Guid id, [FromBody]LeagueDTO value)
        {
            if (id != value.Id)
            {
                return this.BadRequest("Posted league Id does not match the request.");
            }
            IActionResult result = await Execute(_log, async () => await _leagueService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Deletes the specified league.
        /// </summary>
        /// <param name="id">The league identifier.</param>
        /// <returns></returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(typeof(bool), 200)]
        public async Task<IActionResult> Delete(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _leagueService.Delete(id));
            return result;
        }
    }
}
