using DIHL.Application.Core.Interfaces;
using DIHL.DTOs;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace DIHL.Application.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/Penalty")]
    [Authorize]
    public class PenaltyController : BaseApiController
    {
        private readonly IPenaltyService _penaltyService;
        private readonly ILogger _log = Log.ForContext<PenaltyController>();

        public PenaltyController(IPenaltyService penaltyService)
        {
            _penaltyService = penaltyService;
        }

        /// <summary>
        /// Lists all the penalty records.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ProducesResponseType(typeof(List<PenaltyDTO>), 200)]
        public async Task<IActionResult> List()
        {
            IActionResult result = await Execute(_log, async () => await _penaltyService.List());
            return result;
        }

        /// <summary>
        /// Gets the specified penalty.
        /// </summary>
        /// <param name="id">The penalty identifier.</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(PenaltyDTO), 200)]
        public async Task<IActionResult> Get(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _penaltyService.Get(id));
            return result;
        }

        /// <summary>
        /// Upserts an penalty record.
        /// The penalty id is generated by the server.
        /// </summary>
        /// <param name="value">The entity data.</param>
        /// <returns></returns>
        [HttpPost]
        [ProducesResponseType(typeof(PenaltyDTO), 200)]
        public async Task<IActionResult> Post([FromBody]PenaltyDTO value)
        {
            IActionResult result = await Execute(_log, async () => await _penaltyService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Puts the posted penalty data at the specific location.
        /// </summary>
        /// <param name="id">The Id to assign to the penalty.</param>
        /// <param name="value">The penalty data.</param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(PenaltyDTO), 200)]
        public async Task<IActionResult> Put(Guid id, [FromBody]PenaltyDTO value)
        {
            if (id != value.Id)
            {
                return this.BadRequest("Posted penalty Id does not match the request.");
            }
            IActionResult result = await Execute(_log, async () => await _penaltyService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Deletes the specified penalty.
        /// </summary>
        /// <param name="id">The penalty identifier.</param>
        /// <returns></returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(typeof(bool), 200)]
        public async Task<IActionResult> Delete(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _penaltyService.Delete(id));
            return result;
        }
    }
}
