using DIHL.Application.Core.Interfaces;
using DIHL.DTOs;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DIHL.Application.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/Player")]
    public class PlayerController : BaseApiController
    {
        private readonly IPlayerService _playerService;
        private readonly ILogger _log = Log.ForContext<PlayerController>();

        public PlayerController(IPlayerService playerService)
        {
            _playerService = playerService;
        }

        /// <summary>
        /// Lists all the player records.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ProducesResponseType(typeof(List<PlayerDTO>), 200)]
        public async Task<IActionResult> List()
        {
            IActionResult result = await Execute(_log, async () => await _playerService.List());
            return result;
        }

        /// <summary>
        /// Gets the specified player.
        /// </summary>
        /// <param name="id">The player identifier.</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(PlayerDTO), 200)]
        public async Task<IActionResult> Get(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _playerService.Get(id));
            return result;
        }

        /// <summary>
        /// Upserts an player record.
        /// The player id is generated by the server.
        /// </summary>
        /// <param name="value">The entity data.</param>
        /// <returns></returns>
        [HttpPost]
        [ProducesResponseType(typeof(PlayerDTO), 200)]
        public async Task<IActionResult> Post([FromBody]PlayerDTO value)
        {
            IActionResult result = await Execute(_log, async () => await _playerService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Puts the posted player data at the specific location.
        /// </summary>
        /// <param name="id">The Id to assign to the player.</param>
        /// <param name="value">The player data.</param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(PlayerDTO), 200)]
        public async Task<IActionResult> Put(Guid id, [FromBody]PlayerDTO value)
        {
            if (id != value.Id)
            {
                return this.BadRequest("Posted league Id does not match the request.");
            }
            IActionResult result = await Execute(_log, async () => await _playerService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Deletes the specified player.
        /// </summary>
        /// <param name="id">The player identifier.</param>
        /// <returns></returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(typeof(bool), 200)]
        public async Task<IActionResult> Delete(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _playerService.Delete(id));
            return result;
        }
    }
}
