using DIHL.Application.Core.Interfaces;
using DIHL.DTOs;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace DIHL.Application.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/Team")]
    [Authorize]
    public class TeamController : BaseApiController
    {
        private readonly ITeamService _teamService;
        private readonly ILogger _log = Log.ForContext<TeamController>();

        public TeamController(ITeamService teamService)
        {
            _teamService = teamService;
        }

        /// <summary>
        /// Lists all the team records.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ProducesResponseType(typeof(List<TeamDTO>), 200)]
        public async Task<IActionResult> List()
        {
            IActionResult result = await Execute(_log, async () => await _teamService.List());
            return result;
        }

        /// <summary>
        /// Gets the specified team.
        /// </summary>
        /// <param name="id">The team identifier.</param>
        /// <returns></returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(TeamDTO), 200)]
        public async Task<IActionResult> Get(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _teamService.Get(id));
            return result;
        }

        /// <summary>
        /// Upserts an team record.
        /// The team id is generated by the server.
        /// </summary>
        /// <param name="value">The entity data.</param>
        /// <returns></returns>
        [HttpPost]
        [ProducesResponseType(typeof(TeamDTO), 200)]
        public async Task<IActionResult> Post([FromBody]TeamDTO value)
        {
            IActionResult result = await Execute(_log, async () => await _teamService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Puts the posted team data at the specific location.
        /// </summary>
        /// <param name="id">The Id to assign to the team.</param>
        /// <param name="value">The team data.</param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(TeamDTO), 200)]
        public async Task<IActionResult> Put(Guid id, [FromBody]TeamDTO value)
        {
            if (id != value.Id)
            {
                return this.BadRequest("Posted team Id does not match the request.");
            }
            IActionResult result = await Execute(_log, async () => await _teamService.Upsert(value));
            return result;
        }

        /// <summary>
        /// Deletes the specified team.
        /// </summary>
        /// <param name="id">The team identifier.</param>
        /// <returns></returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(typeof(bool), 200)]
        public async Task<IActionResult> Delete(Guid id)
        {
            IActionResult result = await Execute(_log, async () => await _teamService.Delete(id));
            return result;
        }
    }
}
